import type { Activity, ActivityUser, ActivityData } from './types/activity.types';

export const ACTIVITY_TYPE_COLORS: Record<string, { bg: string; border: string; text: string; icon: string }> = {
  commit: {
    bg: 'rgba(33, 150, 243, 0.1)',
    border: 'var(--dt-colors-charts-categorical-blue-default)',
    text: 'var(--dt-colors-charts-categorical-blue-default)',
    icon: '🔷',
  },
  comment: {
    bg: 'rgba(255, 193, 7, 0.1)',
    border: 'var(--dt-colors-charts-categorical-yellow-default)',
    text: 'var(--dt-colors-charts-categorical-yellow-default)',
    icon: '💬',
  },
  task: {
    bg: 'rgba(76, 175, 80, 0.1)',
    border: 'var(--dt-colors-charts-categorical-grass-default)',
    text: 'var(--dt-colors-charts-categorical-grass-default)',
    icon: '✅',
  },
  settings: {
    bg: 'rgba(156, 39, 176, 0.1)',
    border: 'var(--dt-colors-charts-categorical-purple-default)',
    text: 'var(--dt-colors-charts-categorical-purple-default)',
    icon: '⚙️',
  },
  user: {
    bg: 'rgba(158, 158, 158, 0.1)',
    border: 'var(--dt-colors-text-secondary-default)',
    text: 'var(--dt-colors-text-secondary-default)',
    icon: '👤',
  },
  file: {
    bg: 'rgba(255, 152, 0, 0.1)',
    border: 'var(--dt-colors-charts-categorical-sunrise-default)',
    text: 'var(--dt-colors-charts-categorical-sunrise-default)',
    icon: '📄',
  },
  branch: {
    bg: 'rgba(0, 150, 136, 0.1)',
    border: 'var(--dt-colors-charts-categorical-turquoise-default)',
    text: 'var(--dt-colors-charts-categorical-turquoise-default)',
    icon: '🌿',
  },
  pr: {
    bg: 'rgba(233, 30, 99, 0.1)',
    border: 'var(--dt-colors-charts-categorical-pink-default)',
    text: 'var(--dt-colors-charts-categorical-pink-default)',
    icon: '🔀',
  },
};

export const TEAM_MEMBERS: ActivityUser[] = [
  { id: 'user_1', name: 'John Doe', email: 'john@example.com' },
  { id: 'user_2', name: 'Sarah Johnson', email: 'sarah@example.com' },
  { id: 'user_3', name: 'Mike Chen', email: 'mike@example.com' },
  { id: 'user_4', name: 'Emma Davis', email: 'emma@example.com' },
  { id: 'user_5', name: 'Tom Wilson', email: 'tom@example.com' },
];

const createMockActivity = (
  id: string,
  timestamp: string,
  userId: string,
  data: ActivityData
): Activity => ({
  id,
  timestamp,
  user: TEAM_MEMBERS.find(u => u.id === userId) || TEAM_MEMBERS[0],
  data,
});

export const MOCK_ACTIVITIES: Activity[] = [
  // Today's activities (newest first)
  createMockActivity('act_1', new Date(Date.now() - 5 * 60000).toISOString(), 'user_1', {
    type: 'commit',
    commitHash: 'a1b2c3d',
    message: 'Fixed authentication bug in login component',
    branch: 'feature/auth-fix',
    filesChanged: 5,
    additions: 125,
    deletions: 43,
    files: [
      { path: 'src/pages/Login.tsx', additions: 78, deletions: 32 },
      { path: 'src/utils/auth.ts', additions: 32, deletions: 11 },
      { path: 'src/hooks/useAuth.ts', additions: 15, deletions: 0 },
      { path: 'src/types/auth.types.ts', additions: 0, deletions: 0 },
      { path: 'tests/auth.test.ts', additions: 0, deletions: 0 },
    ],
  }),
  createMockActivity('act_2', new Date(Date.now() - 15 * 60000).toISOString(), 'user_2', {
    type: 'comment',
    context: 'Commented on Login.tsx',
    preview: 'Great work on the auth fix! This will resolve the CORS issues we were facing.',
    line: 45,
    replyCount: 2,
    fullText: 'Great work on the auth fix! This will resolve the CORS issues we were facing. Have you tested it against the staging environment?',
  }),
  createMockActivity('act_3', new Date(Date.now() - 30 * 60000).toISOString(), 'user_3', {
    type: 'task',
    taskId: 'TASK-123',
    title: 'Update authentication documentation',
    status: 'completed',
    priority: 'medium',
    assignee: TEAM_MEMBERS[2],
    dueDate: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  }),
  createMockActivity('act_4', new Date(Date.now() - 45 * 60000).toISOString(), 'user_4', {
    type: 'settings',
    settingName: 'Feature Flag: dark-mode',
    beforeValue: 'Disabled',
    afterValue: 'Enabled',
    scope: 'Shared-UI',
  }),

  // Yesterday
  createMockActivity('act_5', new Date(Date.now() - 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'user',
    action: 'joined the project',
  }),
  createMockActivity('act_6', new Date(Date.now() - 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'file',
    operation: 'created',
    filePath: 'src/pages/Dashboard.tsx',
    fileSize: 2560,
  }),
  createMockActivity('act_7', new Date(Date.now() - 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'commit',
    commitHash: 'd4e5f6g',
    message: 'Implement dark mode toggle component',
    branch: 'feature/dark-mode',
    filesChanged: 8,
    additions: 234,
    deletions: 12,
    files: [
      { path: 'src/components/DarkModeToggle.tsx', additions: 120, deletions: 0 },
      { path: 'src/hooks/useDarkMode.ts', additions: 50, deletions: 0 },
      { path: 'src/styles/theme.ts', additions: 64, deletions: 12 },
    ],
  }),
  createMockActivity('act_8', new Date(Date.now() - 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'branch',
    action: 'created',
    branchName: 'feature/new-dashboard',
  }),
  createMockActivity('act_9', new Date(Date.now() - 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'pr',
    action: 'merged',
    prNumber: 284,
    title: 'Add user authentication',
    reviewers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]],
    status: 'merged',
  }),

  // Last 7 days
  createMockActivity('act_10', new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'task',
    taskId: 'TASK-124',
    title: 'Fix navigation bug on mobile',
    status: 'created',
    priority: 'high',
    assignee: TEAM_MEMBERS[0],
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_11', new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'commit',
    commitHash: 'e7f8g9h',
    message: 'Add responsive navigation menu for mobile',
    branch: 'feature/mobile-nav',
    filesChanged: 6,
    additions: 186,
    deletions: 54,
  }),
  createMockActivity('act_12', new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'comment',
    context: 'Commented on src/components/Navigation.tsx',
    preview: 'Please add keyboard navigation support as well. This is important for accessibility.',
    line: 120,
    replyCount: 1,
  }),
  createMockActivity('act_13', new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'task',
    taskId: 'TASK-125',
    title: 'Implement accessibility improvements',
    status: 'in_progress',
    priority: 'high',
    assignee: TEAM_MEMBERS[3],
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_14', new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'file',
    operation: 'created',
    filePath: 'src/utils/accessibility.ts',
    fileSize: 3840,
  }),
  createMockActivity('act_15', new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'settings',
    settingName: 'Analytics Tracking',
    beforeValue: 'Disabled',
    afterValue: 'Enabled',
    scope: 'Project-Wide',
  }),
  createMockActivity('act_16', new Date(Date.now() - 5.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'pr',
    action: 'created',
    prNumber: 285,
    title: 'Add mobile navigation support',
    reviewers: [TEAM_MEMBERS[1], TEAM_MEMBERS[3]],
    status: 'open',
  }),
  createMockActivity('act_17', new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'commit',
    commitHash: 'h0i1j2k',
    message: 'Add unit tests for navigation component',
    branch: 'feature/mobile-nav',
    filesChanged: 3,
    additions: 456,
    deletions: 0,
  }),
  createMockActivity('act_18', new Date(Date.now() - 6.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'branch',
    action: 'created',
    branchName: 'feature/unit-tests',
  }),

  // Last 30 days (older entries)
  createMockActivity('act_19', new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'comment',
    context: 'Commented on src/styles/theme.ts',
    preview: 'The color scheme looks great! Does this match the new brand guidelines?',
    line: 45,
    replyCount: 3,
  }),
  createMockActivity('act_20', new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'task',
    taskId: 'TASK-126',
    title: 'Update component documentation',
    status: 'completed',
    priority: 'low',
    assignee: TEAM_MEMBERS[1],
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_21', new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'commit',
    commitHash: 'l3m4n5o',
    message: 'Refactor component hooks structure',
    branch: 'refactor/hooks',
    filesChanged: 12,
    additions: 345,
    deletions: 289,
  }),
  createMockActivity('act_22', new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'file',
    operation: 'renamed',
    filePath: 'src/utils/helpers.ts',
    previousPath: 'src/utils/utility.ts',
  }),
  createMockActivity('act_23', new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'settings',
    settingName: 'Build Environment',
    beforeValue: 'Development',
    afterValue: 'Production',
    scope: 'CI/CD Pipeline',
  }),
  createMockActivity('act_24', new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'pr',
    action: 'merged',
    prNumber: 286,
    title: 'Update component styles',
    reviewers: [TEAM_MEMBERS[0]],
    status: 'merged',
  }),
  createMockActivity('act_25', new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'commit',
    commitHash: 'p6q7r8s',
    message: 'Add error handling to API requests',
    branch: 'feature/error-handling',
    filesChanged: 7,
    additions: 198,
    deletions: 23,
  }),
  createMockActivity('act_26', new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'task',
    taskId: 'TASK-127',
    title: 'Set up error monitoring',
    status: 'in_progress',
    priority: 'high',
    assignee: TEAM_MEMBERS[2],
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_27', new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'comment',
    context: 'Commented on src/api/client.ts',
    preview: 'Make sure to include retry logic for network timeouts.',
    line: 78,
    replyCount: 0,
  }),
  createMockActivity('act_28', new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'branch',
    action: 'created',
    branchName: 'bugfix/api-timeouts',
  }),
  createMockActivity('act_29', new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'file',
    operation: 'created',
    filePath: 'src/config/api.config.ts',
    fileSize: 1024,
  }),
  createMockActivity('act_30', new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'pr',
    action: 'created',
    prNumber: 287,
    title: 'Add error handling and retry logic',
    reviewers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1], TEAM_MEMBERS[2]],
    status: 'open',
  }),
  createMockActivity('act_31', new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'settings',
    settingName: 'Logging Level',
    beforeValue: 'Warning',
    afterValue: 'Debug',
    scope: 'Development',
  }),
  createMockActivity('act_32', new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'commit',
    commitHash: 't9u0v1w',
    message: 'Implement logging system',
    branch: 'feature/logging',
    filesChanged: 5,
    additions: 267,
    deletions: 15,
  }),
  createMockActivity('act_33', new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'task',
    taskId: 'TASK-128',
    title: 'Document API endpoints',
    status: 'created',
    priority: 'medium',
    assignee: TEAM_MEMBERS[4],
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_34', new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'comment',
    context: 'Commented on API documentation',
    preview: 'Include examples for all endpoints. This will help developers integrate faster.',
    replyCount: 2,
  }),
  createMockActivity('act_35', new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'file',
    operation: 'created',
    filePath: 'docs/api.md',
    fileSize: 4096,
  }),
  createMockActivity('act_36', new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'user',
    action: 'was assigned as reviewer for PR #287',
  }),
  createMockActivity('act_37', new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'branch',
    action: 'created',
    branchName: 'feature/api-documentation',
  }),
  createMockActivity('act_38', new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'commit',
    commitHash: 'x2y3z4a',
    message: 'Add API documentation examples',
    branch: 'feature/api-documentation',
    filesChanged: 4,
    additions: 512,
    deletions: 0,
  }),
  createMockActivity('act_39', new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'pr',
    action: 'merged',
    prNumber: 288,
    title: 'Add API documentation',
    reviewers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]],
    status: 'merged',
  }),
  createMockActivity('act_40', new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'settings',
    settingName: 'API Rate Limiting',
    beforeValue: '100 requests/minute',
    afterValue: '1000 requests/minute',
    scope: 'Production',
  }),
  createMockActivity('act_41', new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'task',
    taskId: 'TASK-129',
    title: 'Performance optimization',
    status: 'completed',
    priority: 'high',
    assignee: TEAM_MEMBERS[3],
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_42', new Date(Date.now() - 29.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'commit',
    commitHash: 'b5c6d7e',
    message: 'Optimize bundle size and load times',
    branch: 'feature/optimization',
    filesChanged: 8,
    additions: 125,
    deletions: 342,
  }),
  createMockActivity('act_43', new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'comment',
    context: 'Commented on performance metrics',
    preview: 'Great improvements! We reduced load time by 30%. This will significantly improve user experience.',
    replyCount: 4,
  }),
  createMockActivity('act_44', new Date(Date.now() - 30.3 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'file',
    operation: 'created',
    filePath: 'src/performance/metrics.ts',
    fileSize: 2048,
  }),
  createMockActivity('act_45', new Date(Date.now() - 30.6 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'branch',
    action: 'created',
    branchName: 'feature/performance-metrics',
  }),
  createMockActivity('act_46', new Date(Date.now() - 30.8 * 24 * 60 * 60 * 1000).toISOString(), 'user_1', {
    type: 'pr',
    action: 'created',
    prNumber: 289,
    title: 'Performance optimizations and metrics',
    reviewers: [TEAM_MEMBERS[1], TEAM_MEMBERS[3]],
    status: 'open',
  }),
  createMockActivity('act_47', new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(), 'user_2', {
    type: 'user',
    action: 'left a review on PR #289',
  }),
  createMockActivity('act_48', new Date(Date.now() - 31.2 * 24 * 60 * 60 * 1000).toISOString(), 'user_3', {
    type: 'settings',
    settingName: 'Cache Duration',
    beforeValue: '5 minutes',
    afterValue: '30 minutes',
    scope: 'API Responses',
  }),
  createMockActivity('act_49', new Date(Date.now() - 31.5 * 24 * 60 * 60 * 1000).toISOString(), 'user_4', {
    type: 'task',
    taskId: 'TASK-130',
    title: 'Add caching strategy',
    status: 'completed',
    priority: 'medium',
    assignee: TEAM_MEMBERS[0],
    dueDate: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
  }),
  createMockActivity('act_50', new Date(Date.now() - 31.8 * 24 * 60 * 60 * 1000).toISOString(), 'user_5', {
    type: 'commit',
    commitHash: 'f8g9h0i',
    message: 'Implement response caching strategy',
    branch: 'feature/caching',
    filesChanged: 6,
    additions: 234,
    deletions: 12,
  }),
];
