import type { Product } from "../types/product.types";

export const mockProducts: Product[] = [
  // Electronics (5 items)
  {
    id: "e1",
    name: "Wireless Headphones",
    emoji: "🎧",
    category: "Electronics",
    price: 79.99,
    stock: 45,
    status: "in-stock",
  },
  {
    id: "e2",
    name: "Smart Watch",
    emoji: "⌚",
    category: "Electronics",
    price: 199.99,
    stock: 12,
    status: "in-stock",
  },
  {
    id: "e3",
    name: "USB-C Cable",
    emoji: "🔌",
    category: "Electronics",
    price: 14.99,
    stock: 200,
    status: "in-stock",
  },
  {
    id: "e4",
    name: "Laptop Stand",
    emoji: "💻",
    category: "Electronics",
    price: 49.99,
    stock: 0,
    status: "out-of-stock",
  },
  {
    id: "e5",
    name: "Bluetooth Speaker",
    emoji: "🔊",
    category: "Electronics",
    price: 59.99,
    stock: 88,
    status: "in-stock",
  },

  // Apparel (5 items)
  {
    id: "a1",
    name: "Cotton T-Shirt",
    emoji: "👕",
    category: "Apparel",
    price: 19.99,
    stock: 150,
    status: "in-stock",
  },
  {
    id: "a2",
    name: "Running Shoes",
    emoji: "👟",
    category: "Apparel",
    price: 89.99,
    stock: 34,
    status: "in-stock",
  },
  {
    id: "a3",
    name: "Winter Jacket",
    emoji: "🧥",
    category: "Apparel",
    price: 129.99,
    stock: 0,
    status: "out-of-stock",
  },
  {
    id: "a4",
    name: "Baseball Cap",
    emoji: "🧢",
    category: "Apparel",
    price: 24.99,
    stock: 67,
    status: "in-stock",
  },
  {
    id: "a5",
    name: "Leather Belt",
    emoji: "👔",
    category: "Apparel",
    price: 34.99,
    stock: 42,
    status: "in-stock",
  },

  // Home & Garden (5 items)
  {
    id: "h1",
    name: "Coffee Maker",
    emoji: "☕",
    category: "Home & Garden",
    price: 79.99,
    stock: 28,
    status: "in-stock",
  },
  {
    id: "h2",
    name: "Garden Hose",
    emoji: "🌱",
    category: "Home & Garden",
    price: 29.99,
    stock: 0,
    status: "out-of-stock",
  },
  {
    id: "h3",
    name: "Table Lamp",
    emoji: "💡",
    category: "Home & Garden",
    price: 44.99,
    stock: 56,
    status: "in-stock",
  },
  {
    id: "h4",
    name: "Throw Pillow",
    emoji: "🛋️",
    category: "Home & Garden",
    price: 22.99,
    stock: 93,
    status: "in-stock",
  },
  {
    id: "h5",
    name: "Wall Clock",
    emoji: "🕐",
    category: "Home & Garden",
    price: 39.99,
    stock: 18,
    status: "in-stock",
  },

  // Sports (5 items)
  {
    id: "s1",
    name: "Yoga Mat",
    emoji: "🧘",
    category: "Sports",
    price: 29.99,
    stock: 76,
    status: "in-stock",
  },
  {
    id: "s2",
    name: "Basketball",
    emoji: "🏀",
    category: "Sports",
    price: 34.99,
    stock: 48,
    status: "in-stock",
  },
  {
    id: "s3",
    name: "Tennis Racket",
    emoji: "🎾",
    category: "Sports",
    price: 89.99,
    stock: 0,
    status: "out-of-stock",
  },
  {
    id: "s4",
    name: "Dumbbell Set",
    emoji: "🏋️",
    category: "Sports",
    price: 149.99,
    stock: 23,
    status: "in-stock",
  },
  {
    id: "s5",
    name: "Swimming Goggles",
    emoji: "🏊",
    category: "Sports",
    price: 24.99,
    stock: 61,
    status: "in-stock",
  },

  // Books (5 items)
  {
    id: "b1",
    name: "Mystery Novel",
    emoji: "📚",
    category: "Books",
    price: 14.99,
    stock: 102,
    status: "in-stock",
  },
  {
    id: "b2",
    name: "Cookbook",
    emoji: "📖",
    category: "Books",
    price: 24.99,
    stock: 37,
    status: "in-stock",
  },
  {
    id: "b3",
    name: "Science Fiction",
    emoji: "📕",
    category: "Books",
    price: 16.99,
    stock: 0,
    status: "out-of-stock",
  },
  {
    id: "b4",
    name: "Travel Guide",
    emoji: "🗺️",
    category: "Books",
    price: 19.99,
    stock: 44,
    status: "in-stock",
  },
  {
    id: "b5",
    name: "Biography",
    emoji: "📘",
    category: "Books",
    price: 22.99,
    stock: 68,
    status: "in-stock",
  },
];
