export type Product = {
  productId: string;
  name: string;
  category: 'Electronics' | 'Apparel' | 'Books' | 'Home' | 'Sports';
  unitPrice: number; // USD cents
  stockCount: number;
  available: boolean;
  imageEmoji: string;
};

export const mockProducts: Product[] = [
  // Electronics (5 products)
  {
    productId: 'PROD-001',
    name: 'Wireless Headphones',
    category: 'Electronics',
    unitPrice: 7999,
    stockCount: 45,
    available: true,
    imageEmoji: '🎧',
  },
  {
    productId: 'PROD-002',
    name: 'Smartphone Pro',
    category: 'Electronics',
    unitPrice: 89999,
    stockCount: 12,
    available: true,
    imageEmoji: '📱',
  },
  {
    productId: 'PROD-003',
    name: 'Laptop Computer',
    category: 'Electronics',
    unitPrice: 129999,
    stockCount: 8,
    available: true,
    imageEmoji: '💻',
  },
  {
    productId: 'PROD-004',
    name: 'Smart Watch',
    category: 'Electronics',
    unitPrice: 29999,
    stockCount: 0,
    available: false,
    imageEmoji: '⌚',
  },
  {
    productId: 'PROD-005',
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    unitPrice: 4999,
    stockCount: 67,
    available: true,
    imageEmoji: '🔊',
  },
  // Apparel (5 products)
  {
    productId: 'PROD-006',
    name: 'Cotton T-Shirt',
    category: 'Apparel',
    unitPrice: 1999,
    stockCount: 150,
    available: true,
    imageEmoji: '👕',
  },
  {
    productId: 'PROD-007',
    name: 'Running Shoes',
    category: 'Apparel',
    unitPrice: 8999,
    stockCount: 34,
    available: true,
    imageEmoji: '👟',
  },
  {
    productId: 'PROD-008',
    name: 'Winter Jacket',
    category: 'Apparel',
    unitPrice: 12999,
    stockCount: 0,
    available: false,
    imageEmoji: '🧥',
  },
  {
    productId: 'PROD-009',
    name: 'Baseball Cap',
    category: 'Apparel',
    unitPrice: 1499,
    stockCount: 89,
    available: true,
    imageEmoji: '🧢',
  },
  {
    productId: 'PROD-010',
    name: 'Sunglasses',
    category: 'Apparel',
    unitPrice: 5999,
    stockCount: 42,
    available: true,
    imageEmoji: '🕶️',
  },
  // Books (5 products)
  {
    productId: 'PROD-011',
    name: 'The Great Novel',
    category: 'Books',
    unitPrice: 1699,
    stockCount: 120,
    available: true,
    imageEmoji: '📚',
  },
  {
    productId: 'PROD-012',
    name: 'Cookbook Deluxe',
    category: 'Books',
    unitPrice: 2499,
    stockCount: 56,
    available: true,
    imageEmoji: '📖',
  },
  {
    productId: 'PROD-013',
    name: 'Programming Guide',
    category: 'Books',
    unitPrice: 4999,
    stockCount: 0,
    available: false,
    imageEmoji: '💻',
  },
  {
    productId: 'PROD-014',
    name: 'Travel Atlas',
    category: 'Books',
    unitPrice: 2999,
    stockCount: 23,
    available: true,
    imageEmoji: '🗺️',
  },
  {
    productId: 'PROD-015',
    name: 'Mystery Thriller',
    category: 'Books',
    unitPrice: 1299,
    stockCount: 200,
    available: true,
    imageEmoji: '📕',
  },
  // Home (5 products)
  {
    productId: 'PROD-016',
    name: 'Coffee Maker',
    category: 'Home',
    unitPrice: 7999,
    stockCount: 28,
    available: true,
    imageEmoji: '☕',
  },
  {
    productId: 'PROD-017',
    name: 'Table Lamp',
    category: 'Home',
    unitPrice: 3999,
    stockCount: 0,
    available: false,
    imageEmoji: '💡',
  },
  {
    productId: 'PROD-018',
    name: 'Cozy Blanket',
    category: 'Home',
    unitPrice: 4499,
    stockCount: 75,
    available: true,
    imageEmoji: '🛋️',
  },
  {
    productId: 'PROD-019',
    name: 'Plant Pot Set',
    category: 'Home',
    unitPrice: 1999,
    stockCount: 110,
    available: true,
    imageEmoji: '🪴',
  },
  {
    productId: 'PROD-020',
    name: 'Wall Clock',
    category: 'Home',
    unitPrice: 2999,
    stockCount: 45,
    available: true,
    imageEmoji: '🕐',
  },
  // Sports (5 products)
  {
    productId: 'PROD-021',
    name: 'Basketball',
    category: 'Sports',
    unitPrice: 2999,
    stockCount: 62,
    available: true,
    imageEmoji: '🏀',
  },
  {
    productId: 'PROD-022',
    name: 'Yoga Mat',
    category: 'Sports',
    unitPrice: 3499,
    stockCount: 0,
    available: false,
    imageEmoji: '🧘',
  },
  {
    productId: 'PROD-023',
    name: 'Tennis Racket',
    category: 'Sports',
    unitPrice: 8999,
    stockCount: 18,
    available: true,
    imageEmoji: '🎾',
  },
  {
    productId: 'PROD-024',
    name: 'Dumbbells Set',
    category: 'Sports',
    unitPrice: 6999,
    stockCount: 32,
    available: true,
    imageEmoji: '🏋️',
  },
  {
    productId: 'PROD-025',
    name: 'Mountain Bike',
    category: 'Sports',
    unitPrice: 45999,
    stockCount: 5,
    available: true,
    imageEmoji: '🚵',
  },
];
